- name: Ensure directory structure exists
  file:
    path: '{{ templates_destination }}-{{ index }}/{{ item.path }}'
    state: directory
  with_filetree: '{{ templates_source }}'
  when: item.state == 'directory'

- name: Ensure files are populated from templates
  template:
    src: '{{ item.src }}'
    dest: '{{ templates_destination }}-{{ index }}/{{ item.path }}'
  with_filetree: '{{ templates_source }}'
  when: item.state == 'file'