---
- hosts: all
  become: true
  tasks:
    - include_role:
        name: geerlingguy.mysql
    
    # - name: "MYSQL | Run migrations"
    #   command: mysql -u root -proot < /home/ubuntu/challenge.sql