---
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - name: Install python2 for Ansible
      raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
      register: output
      changed_when: output.stdout != ""
    - name: Gathering Facts
      setup:
  tasks:
    - include_role:
        name: geerlingguy.mysql
    
    # - name: "MYSQL | Run migrations"
    #   command: mysql -u root -proot < /home/ubuntu/challenge.sql